### ISSUE TITLE
feature (info) request : export TypeScript interfaces only locally

### ISSUE THREAD

**Issue by SvenMeyer** [defi-wonderland/interface-exporter-action#55]
(How) Can I export TypeScript interfaces only locally, not exporting an npm package ?

**Comment by gas1cent** [comment]
@SvenMeyer hello! This is a wrong tool if you want to export packages only locally, but we have a script in another repo that does the job. You can pretty much copy-paste it and adjust the package name, description, etc.
https://github.com/defi-wonderland/price-oracle-v1-core-private/blob/dev/interfaces-exporter.js
